definitions:
  models.District:
    properties:
      city_id:
        type: integer
      id:
        type: integer
      name:
        type: string
      properties: {}
    type: object
  models.Place:
    properties:
      city_id:
        type: integer
      district_id:
        type: integer
      id:
        type: integer
      name:
        type: string
      properties: {}
      tags:
        items:
          $ref: '#/definitions/models.Tag'
        type: array
    type: object
  models.PlaceCreate:
    properties:
      city_id:
        type: integer
      district_id:
        type: integer
      name:
        type: string
      properties: {}
      tag_ids:
        items:
          type: integer
        type: array
    type: object
  models.PlaceIDWithPosition:
    properties:
      place_id:
        type: integer
      position:
        type: integer
    type: object
  models.PlaceReview:
    properties:
      author_id:
        type: integer
      id:
        type: integer
      mark:
        type: number
      place_id:
        type: integer
      properties: {}
    type: object
  models.PlaceReviewCreate:
    properties:
      author_id:
        type: integer
      mark:
        type: number
      place_id:
        type: integer
      properties: {}
    type: object
  models.PlaceWithPosition:
    properties:
      place:
        $ref: '#/definitions/models.Place'
      position:
        type: integer
    type: object
  models.ReviewUpdate:
    properties:
      id:
        type: integer
      mark:
        type: number
      properties: {}
    type: object
  models.Route:
    properties:
      city_id:
        type: integer
      id:
        type: integer
      name:
        type: string
      places:
        items:
          $ref: '#/definitions/models.PlaceWithPosition'
        type: array
      price:
        type: integer
      properties: {}
      tags:
        items:
          $ref: '#/definitions/models.Tag'
        type: array
    type: object
  models.RouteCreate:
    properties:
      city_id:
        type: integer
      name:
        type: string
      places:
        items:
          $ref: '#/definitions/models.PlaceIDWithPosition'
        type: array
      price:
        type: integer
      properties: {}
      tag_ids:
        items:
          type: integer
        type: array
    type: object
  models.RouteReview:
    properties:
      author_id:
        type: integer
      id:
        type: integer
      mark:
        type: number
      properties: {}
      route_id:
        type: integer
    type: object
  models.RouteReviewCreate:
    properties:
      author_id:
        type: integer
      mark:
        type: number
      properties: {}
      route_id:
        type: integer
    type: object
  models.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.TagCreate:
    properties:
      name:
        type: string
    type: object
  swagger.Filters:
    properties:
      city_id:
        type: integer
      district_id:
        type: integer
      name:
        type: string
      pagination_page:
        type: integer
      tag_ids:
        items:
          type: integer
        type: array
    type: object
  swagger.GetByAuthor:
    properties:
      place_reviews:
        items:
          $ref: '#/definitions/models.PlaceReview'
        type: array
      route_reviews:
        items:
          $ref: '#/definitions/models.RouteReview'
        type: array
    type: object
info:
  contact: {}
paths:
  /district/by_city_id:
    get:
      consumes:
      - application/json
      parameters:
      - description: City id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            items:
              $ref: '#/definitions/models.District'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - district
  /place/by_id:
    get:
      consumes:
      - application/json
      parameters:
      - description: Place id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            $ref: '#/definitions/models.Place'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - place
  /place/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Place with tag ids create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.PlaceCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created place with id
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - place
  /place/get_all_with_filter:
    put:
      consumes:
      - application/json
      parameters:
      - description: Filters
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/swagger.Filters'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            items:
              $ref: '#/definitions/models.Place'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - place
  /review/author:
    get:
      consumes:
      - application/json
      parameters:
      - description: author id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            $ref: '#/definitions/swagger.GetByAuthor'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /review/create_on_place:
    post:
      consumes:
      - application/json
      parameters:
      - description: place review create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.PlaceReviewCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created route review with id
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /review/create_on_route:
    post:
      consumes:
      - application/json
      parameters:
      - description: Route review create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RouteReviewCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created route review with id
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /review/place:
    get:
      consumes:
      - application/json
      parameters:
      - description: place id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            items:
              $ref: '#/definitions/models.PlaceReview'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /review/route:
    get:
      consumes:
      - application/json
      parameters:
      - description: route id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            items:
              $ref: '#/definitions/models.RouteReview'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /review/update_on_place:
    put:
      consumes:
      - application/json
      parameters:
      - description: place review id
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.ReviewUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /review/update_on_route:
    put:
      consumes:
      - application/json
      parameters:
      - description: route review id
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.ReviewUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - review
  /route/by_id:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            $ref: '#/definitions/models.Route'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - route
  /route/by_page:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            items:
              $ref: '#/definitions/models.Route'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - route
  /route/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Route with tag ids and place ids create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RouteCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created route with id
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - route
  /tag/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Tag create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.TagCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created tag with id
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - tag
  /tag/get_all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created tag with id
          schema:
            items:
              $ref: '#/definitions/models.Tag'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - tag
swagger: "2.0"
